name: iConnect Server V1

on:
  pull_request:
    branches: [main]  
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Debug Environment
        run: |
            echo "Current PATH: $PATH"
            pm2 --version
            npm --version

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            /home/azureuser/iconnect
            git pull origin main  
            git status
            pm2 kill
            export NODE_ENV=production
            cd server
            npm install
            npm run tsc
            npm run start:prod


